worker_processes auto;

events {
    worker_connections  1024;
}

http {

    include             mime.types;
    types {
      text/csv csv;
    }
    sendfile            on;
    keepalive_timeout   65;
    log_format  main    '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

    map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }

    server {

        listen 80;

        location / {

            # Serve static files all the time
            root /home/tjpalanca/public/tjblog/;

            # Auto Index
            autoindex on;

        }
    }

}
