---
title: "Contact"
description: >-
  How you can get in contact via social media, subscribe to the blog, or via
  good old-fashioned e-mail.
---

## Social

Contact via social media channels to connect personally or professionally! Always happy to interact and collaborate with people who share the same mission.

* <a href="https://www.facebook.com/tjpalanca" target="_blank" tyle="color:#00000;"><i class='fab fa-facebook-square fa-2x'></i>&nbsp;&nbsp;<strong>Facebook (Personal)</strong></a>
* <a href="https://www.facebook.com/tjpalanca.blog" target="_blank" style="color:#3b5998;"><i class='fab fa-facebook-square fa-2x'></i>&nbsp;&nbsp;<strong>Facebook (Page)</strong></a>
* <a href="https://twitter.com/tjpalanca" target="_blank" style="color:#55acee;"><i class='fab fa-twitter fa-2x'></i>&nbsp;<strong>Twitter</strong></a>
* <a href="https://www.github.com/tjpalanca" target="_blank" style="color:#666666;"><i class='fab fa-github fa-2x'></i>&nbsp;<strong>GitHub</strong></a>
* <a href="https://www.linkedin.com/in/tjpalanca" target="_blank" style="color:#4875b4;"><i class='fab fa-linkedin fa-2x'></i>&nbsp;<strong>LinkedIn</strong></a>

## Subscribe

Subscribe to get e-mail or RSS updates to any new content on the blog. The information will be used only for pushing out updates and will never be shared with third-parties.

Subscribe via <a href="https://feeds.feedburner.com/tjpalanca-blog" style="border: 0px solid; background-color:#FF6600; color:white;" class="uk-button uk-button-default" target="_blank"><i class='fa fa-rss-square fa-1x'></i>&nbsp;<strong>RSS</strong></a> or e-mail subscription through the form below:

<form style="border:0px solid #ccc; padding:3px; text-align:left;" action="https://feedburner.google.com/fb/a/mailverify" method="post" target="popupwindow" onsubmit="window.open('https://feedburner.google.com/fb/a/mailverify?uri=tjpalanca-blog', 'popupwindow', 'scrollbars=yes,width=550,height=520');return true">
<p><strong>Enter your email address:</strong></p>
<p><input type="text" class="uk-input" name="email" style="border:1px solid #ccc;"/></p>
<input type="hidden" value="tjpalanca-blog" name="uri"/>
<input type="hidden" name="loc" value="en_US"/>
<button type="submit" class="uk-button uk-button-default" style="background-color: #2cbf53; color: white;">
    <i class="fa fa-envelope-open fa-1x"></i>&nbsp;&nbsp;Subscribe
</button>
</form>

## E-mail

E-mail me directly for **guest contributions, consulting project offers, post corrections, syndication offers, and to collaborate on any project**. I'm reachable at <a href="mailto:mail@tjpalanca.com" style="border: 0px solid; background-color:gray; color:white;" class="uk-button uk-button-default" target="_blank"><i class='fa fa-envelope fa-1x' target="_blank"></i>&nbsp;<strong>mail&#64;tjpalanca.com</strong></a>.

