---
title: "FAQ and Policies"
date: 2018-04-06
output: 
  distill::distill_article:
    toc: true
---

## Frequently Asked Questions

### Can I reuse/republish your article, or parts of it, in my blog/newspaper/publication?

I would love to contribute, but I just need to take a look at your content. Please see the copyright policy below for complete information. Please contact me at [mail@tjpalanca.com](mailto:mail@tjpalanca.com).

### Can I have the data or computations that you used?

Please see the [copyright policy](#copyright) for complete information. I generally allow requests for non-profit/educational purposes with attribution.

### I think you have an error in this article. How can I correct it?

Please comment on the article and check the [comments policy](#comments). We are always welcome to comments that bring data closer to reality. 

### My comment was disapproved. Why?

Please see if you have violated the [comment policy](#comments). Otherwise, please contact me through at [mail@tjpalanca.com](mailto:mail@tjpalanca.com) if you think it was disapproved unfairly. 

### Who are you?

Please take a look at the [About](about.html#about-me) page. 

### Can I contribute my article to your blog?

I would be happy to publish original contributions that are in line with the blog theme. Please see the [contributions policy](#contributions).

-----

## Policies

These policies apply to content on this site, the [related Facebook page](http://facebook.com/tjpalanca.blog), and linked Github repositories.

### Copyright

If you would like to use any content for your own work, I will provide permission under the following conditions:

* Please contact me first via [mail@tjpalanca.com](mailto:mail@tjpalanca.com).
* Unless explicit written or e-mail permission has been provided, you may not use any content.
* This content may not be used for commercial purposes.
* I retain the right to use this content for any purpose.
* I would appreciate a copy of the paper or a link to your work.
* Not all the content on this site is fit for academic publication. It might be better to request the original data and perform your own analysis.
* No warranties are provided.

### Content

I try to adhere to journalistic standards whenever I write, but I may have opinions that I will not hesitate to express in the articles. I will, however, clearly state that this is simply my opinion and  not a direct implication of the data presented.

### Comments

We welcome comments that generate discussion, provide new ideas, corrections, or constructive criticism, and engage others in the conversation. We want to create an atmosphere of intellectual discipline in the comments. Discussion of a political nature should attempt to adhere to facts and logical reasoning. Excessive partisanship is discouraged. 

We do not encourage comments that only serve to insult and defame, or are otherwise off-topic. Frequent offenders will be banned.

Registered Disqus comments are not moderated. Unregistered comments are moderated automatically to prevent spam comments. If you feel that a commenter is exceeding the limits of healthy discussion, or if your comment was disapproved unfairly, please contact me through [mail@tjpalanca.com](mailto:mail@tjpalanca.com).

### Contributions

I would be thrilled for an interested reader to contribute to this blog, or connect with me through his own data blog. I am looking for posts that use data to shed light on various issues - they don't have to be serious issues; even the trivial can be interesting at times. Posts that react to my articles or use the underlying data to generate insight are also welcome.

You may send these contributions to [mail@tjpalanca.com](mailto:mail@tjpalanca.com) with subject Blog Contribution.

- - - - -

## Privacy Policy

This privacy policy has been compiled to better serve those who are concerned with how their 'Personally Identifiable Information' (PII) is being used online. PII, as described in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.

### What personal information do we collect from the people that visit our blog, website or app?

When ordering or registering on our site, as appropriate, you may be asked to enter your name, email address or other details to help you with your experience.

### When do we collect information?

We collect information from you when you subscribe to a newsletter, respond to a survey, fill out a form or enter information on our site.

### How do we use your information?

We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:

  * To personalize your experience and to allow us to deliver the type of content and product offerings in which you are most interested.
  * To send periodic emails regarding your order or other products and services.

### How do we protect your information?

We do not use vulnerability scanning and/or scanning to PCI standards.
We only provide articles and information. We never ask for credit card numbers.
We use regular Malware Scanning.

We do not use an SSL certificate

  * We only provide articles and information. We never ask for personal or private information like names, email addresses, or credit card numbers.

### Do we use 'cookies'?

Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.

We use cookies to:

  * Compile aggregate data about site traffic and site interactions in order to offer better site experiences and tools in the future. We may also use trusted third-party services that track this information on our behalf.

You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser settings. Since browser is a little different, look at your browser's Help Menu to learn the correct way to modify your cookies.

If you turn cookies off, Some of the features that make your site experience more efficient may not function properly.It won't affect the user's experience that make your site experience more efficient and may not function properly.

### Third-party disclosure

We do not sell, trade, or otherwise transfer to outside parties your Personally Identifiable Information.

### Third-party links

Occasionally, at our discretion, we may include or offer third-party products or services on our website. These third-party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.

### Google

Google's advertising requirements can be summed up by Google's Advertising Principles. They are put in place to provide a positive experience for users. https://support.google.com/adwordspolicy/answer/1316548?hl=en 

We use Google AdSense Advertising on our website.

Google, as a third-party vendor, uses cookies to serve ads on our site. Google's use of the DART cookie enables it to serve ads to our users based on previous visits to our site and other sites on the Internet. Users may opt-out of the use of the DART cookie by visiting the Google Ad and Content Network privacy policy.

We have implemented the following:

  * Remarketing with Google AdSense
  * Google Display Network Impression Reporting
  * Demographics and Interests Reporting
  * DoubleClick Platform Integration

We, along with third-party vendors such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together to compile data regarding user interactions with ad impressions and other ad service functions as they relate to our website.

Opting out:
Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising Initiative Opt Out page or by using the Google Analytics Opt Out Browser add on.

### California Online Privacy Protection Act

CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law's reach stretches well beyond California to require any person or company in the United States (and conceivably the world) that operates websites collecting Personally Identifiable Information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals or companies with whom it is being shared. - See more at: http://consumercal.org/california-online-privacy-protection-act-caloppa/#sthash.0FdRbT51.dpuf

According to CalOPPA, we agree to the following:
Users can visit our site anonymously.
Once this privacy policy is created, we will add a link to it on our home page or as a minimum, on the first significant page after entering our website.
Our Privacy Policy link includes the word 'Privacy' and can easily be found on the page specified above.

You will be notified of any Privacy Policy changes:

  * On our Privacy Policy Page
Can change your personal information:
  * By emailing us

How does our site handle Do Not Track signals?
We honor Do Not Track signals and Do Not Track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place.

Does our site allow third-party behavioral tracking?
It's also important to note that we allow third-party behavioral tracking

COPPA (Children Online Privacy Protection Act)

When it comes to the collection of personal information from children under the age of 13 years old, the Children's Online Privacy Protection Act (COPPA) puts parents in control. The Federal Trade Commission, United States' consumer protection agency, enforces the COPPA Rule, which spells out what operators of websites and online services must do to protect children's privacy and safety online.

We do not specifically market to children under the age of 13 years old.

### Fair Information Practices

The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.

In order to be in line with Fair Information Practices we will take the following responsive action, should a data breach occur:

We will notify you via email

  * Within 7 business days

We also agree to the Individual Redress Principle which requires that individuals have the right to legally pursue enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or government agencies to investigate and/or prosecute non-compliance by data processors.

### CAN SPAM Act

The CAN-SPAM Act is a law that sets the rules for commercial email, establishes requirements for commercial messages, gives recipients the right to have emails stopped from being sent to them, and spells out tough penalties for violations.

We collect your email address in order to:

  * Send information, respond to inquiries, and/or other requests or questions
  * Market to our mailing list or continue to send emails to our clients after the original transaction has occurred.

To be in accordance with CANSPAM, we agree to the following:

  * Not use false or misleading subjects or email addresses.
  * Identify the message as an advertisement in some reasonable way.
  * Include the physical address of our business or site headquarters.
  * Monitor third-party email marketing services for compliance, if one is used.
  * Honor opt-out/unsubscribe requests quickly.
  * Allow users to unsubscribe by using the link at the bottom of each email.

If at any time you would like to unsubscribe from receiving future emails, you can email us at mail@tjpalanca.com and we will promptly remove you from ALL correspondence.

### Contacting Us

If there are any questions regarding this privacy policy, you may contact us at mail@tjpalanca.com.
